services:
  db:
    image: postgres:16
    container_name: nabra-postgres
    environment:
      POSTGRES_DB: nabra
      POSTGRES_USER: postgres.sdkejfgdqrovweyustoh
      POSTGRES_PASSWORD: Zqdg5r1Yuax9XJZY
    ports:
      - "5432:5432"
    volumes:
      - nabra_pgdata:/var/lib/postgresql/data
volumes:
  nabra_pgdata:
