spring:
  application:
    name: nabra-backend

  datasource:
     url: jdbc:postgresql://ep-jolly-unit-ag2asz3z-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_y72RlzPbYqZu&sslmode=require&channelBinding=require

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: odehteam935@gmail.com
    password: towdnaeenrkzeuhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

app:
  security:
    jwt:
      secret: "change-me-change-me-change-me-change-me"
      expirationSeconds: 86400

  frontend:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "http://localhost:4200"

  ai:
    lipreading:
      baseUrl: ""
    prediction:
      baseUrl: ""
    stt:
      baseUrl: ""

logging:
  level:
    org.hibernate.SQL: debug

# ✅ Google OAuth (هام)
google:
  oauth:
    client-id: "839005087126-rc1kc0ujab07u2njkcc2ara0pcvcj3qh.apps.googleusercontent.com"
