package com.nabra.backend.modules.lipreading.controller;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nabra.backend.common.model.Enums.SessionInputType;
import com.nabra.backend.common.model.Enums.SessionOutputType;
import com.nabra.backend.common.web.SecurityUtils;
import com.nabra.backend.modules.lipreading.dto.LipReadingDtos;
import com.nabra.backend.modules.lipreading.service.LipReadingService;
import com.nabra.backend.modules.sessionhistory.service.SessionService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.PreDestroy;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.*;

import java.nio.file.Files;
import java.nio.file.Path;

@RestController
@RequestMapping("/api/v1/lipreading")
@RequiredArgsConstructor
@Tag(name = "Lip Reading")
public class LipReadingController {
    // Persistent audio worker fields
    private static final String AUDIO_WORK_DIR = "src/main/java/com/nabra/backend/modules/lipreading/avsrModels/audio model";
    private static final String AUDIO_WORKER_SCRIPT = "audio_worker.py";
    private final Object audioWorkerLock = new Object();
    private volatile Process audioWorkerProcess;
    private volatile java.io.BufferedWriter audioWorkerStdin;
    private volatile java.io.BufferedReader audioWorkerStdout;

  private static final String STATUS_QUEUED = "QUEUED";
  private static final String STATUS_PROCESSING = "PROCESSING";
  private static final String STATUS_COMPLETED = "COMPLETED";
  private static final String STATUS_FAILED = "FAILED";
  private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
  private static final String AVSR_WORK_DIR = "src/main/java/com/nabra/backend/modules/lipreading/avsrModels/3D ResNet-18";
  private static final String AVSR_WORKER_SCRIPT = "avsr_batch_fusion_worker.py";

  private static final class FusionJob {
    private final String userId;
    private volatile String status;
    private volatile String rawOutput;
    private volatile JsonNode parsedResult;
    private volatile String error;

    private FusionJob(String status, String userId) {
      this.status = status;
      this.userId = userId;
    }
  }
// Simple health check endpoint
  @GetMapping("/ping")
  public ResponseEntity<String> ping() {
    writeLog("/ping", "INFO", "Ping request received");
    return ResponseEntity.ok("Backend is reachable");
  }

  private static final String LOG_FILE_PATH = "fusion_backend.log";

  // The constructor is generated by Lombok's @RequiredArgsConstructor
  // If log file deletion is needed, move this logic elsewhere (e.g., an @PostConstruct method)

  private void writeLog(String endpoint, String status, String details) {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(LOG_FILE_PATH, true))) {
      writer.write(LocalDateTime.now() + " | " + endpoint + " | " + status + " | " + details + "\n");
    } catch (IOException ignored) {}
  }

  private final LipReadingService lipReadingService;
  private final SessionService sessionService;
  private static final Logger log = LoggerFactory.getLogger(LipReadingController.class);
  private final Map<String, FusionJob> fusionJobs = new ConcurrentHashMap<>();
  private final ExecutorService fusionExecutor = Executors.newFixedThreadPool(1);
  private final Object fusionWorkerLock = new Object();
  private volatile Process fusionWorkerProcess;
  private volatile java.io.BufferedWriter fusionWorkerStdin;
  private volatile java.io.BufferedReader fusionWorkerStdout;

  @PreDestroy
  public void shutdownFusionExecutor() {
    stopFusionWorker();
    fusionExecutor.shutdown();
  }

  /**
   * Cloud inference endpoint (conditional feature in SRS). Offline inference is
   * done on-device.
   */
  @PostMapping("/infer")
  public ResponseEntity<LipReadingDtos.LipReadingResponse> infer(
      @Valid @RequestBody LipReadingDtos.LipReadingRequest req) {
    String userId = SecurityUtils.currentPrincipal().getUserId();
    try {
      LipReadingDtos.LipReadingResponse response = lipReadingService.infer(req);
      saveCompletedSession(
          userId,
          req.inputType(),
          req.outputType(),
          response.recognizedText(),
          response.synthesizedAudioUrl(),
          response.confidence(),
          "Lip inference completed"
      );
      return ResponseEntity.ok(response);
    } catch (Exception ex) {
      saveFailedSession(userId, req.inputType(), req.outputType(), ex.getMessage(), "Lip inference failed");
      throw ex;
    }
  }

  @PostMapping("/avsr/fuse")
  public ResponseEntity<LipReadingDtos.AvsrFusionResponse> fuse(@RequestBody LipReadingDtos.AvsrFusionRequest req) {
    String userId = SecurityUtils.currentPrincipal().getUserId();
    SessionInputType inputType = (req.videoPath() == null || req.videoPath().isBlank())
        ? SessionInputType.LIVE
        : SessionInputType.RECORDED;

    try {
      LipReadingDtos.AvsrFusionResponse response = lipReadingService.fuse(req);
      saveCompletedSession(
          userId,
          inputType,
          SessionOutputType.TEXT,
          response.finalWord(),
          null,
          response.similarity(),
          response.fusionReason()
      );
      return ResponseEntity.ok(response);
    } catch (Exception ex) {
      saveFailedSession(userId, inputType, SessionOutputType.TEXT, ex.getMessage(), "AVSR fusion failed");
      throw ex;
    }
  }

  @PostMapping(value = "/avsr/fuse-files", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<Object> fuseFiles(
      @RequestParam("audioFile") MultipartFile audioFile,
      @RequestParam("videoFile") MultipartFile videoFile,
      @RequestParam(value = "wait", defaultValue = "true") boolean wait,
      @RequestParam(value = "timeoutSeconds", defaultValue = "180") long timeoutSeconds,
      @RequestParam(value = "fast", defaultValue = "false") boolean fast,
      @RequestParam(value = "frameCount", required = false) Integer frameCount,
      @RequestParam(value = "sessionId", required = false) String sessionId) throws Exception {
    String userId = SecurityUtils.currentPrincipal().getUserId();
    if (sessionId == null || sessionId.isEmpty()) {
      sessionId = UUID.randomUUID().toString();
    }
    log.info("Received fuse-files request");
    log.info("Request received for /fuse-files");
    writeLog("/fuse-files", "START", "Request received");

        if (audioFile == null || audioFile.isEmpty()) {
          writeLog("/fuse-files", "REFUSED", "Missing or empty audioFile");
          throw new IllegalArgumentException("audioFile is required");
        }
        if (videoFile == null || videoFile.isEmpty()) {
          writeLog("/fuse-files", "REFUSED", "Missing or empty videoFile");
          throw new IllegalArgumentException("videoFile is required");
        }

    Path audioTemp = Files.createTempFile("fuse-audio-", extensionOf(audioFile.getOriginalFilename()));
    Path videoTemp = Files.createTempFile("fuse-video-", extensionOf(videoFile.getOriginalFilename()));
    try {
      audioFile.transferTo(audioTemp);
      videoFile.transferTo(videoTemp);
      log.info("Audio file saved as: {}", audioTemp.getFileName());
      log.info("Video file saved as: {}", videoTemp.getFileName());
      writeLog("/fuse-files", "FILES", "Audio: " + audioTemp.getFileName() + ", Video: " + videoTemp.getFileName());
    } catch (Exception ex) {
      deleteQuietly(audioTemp);
      deleteQuietly(videoTemp);
      throw ex;
    }

    String jobId = UUID.randomUUID().toString();
    fusionJobs.put(jobId, new FusionJob(STATUS_QUEUED, userId));
    CompletableFuture<Void> jobFuture = CompletableFuture
      .runAsync(() -> runFusionJob(jobId, audioTemp, videoTemp, fast, frameCount), fusionExecutor);

    writeLog("/fuse-files", "ACCEPTED", "Fusion job queued: " + jobId);

    if (wait) {
      try {
        jobFuture.get(Math.max(1L, timeoutSeconds), TimeUnit.SECONDS);
        FusionJob completedJob = fusionJobs.get(jobId);
        if (completedJob == null) {
          return ResponseEntity.status(500).body(Map.of(
              "sessionId", sessionId,
              "jobId", jobId,
              "error", "Fusion failed: missing job state"
          ));
        }
        if (STATUS_COMPLETED.equals(completedJob.status)) {
          Object result = completedJob.parsedResult != null ? completedJob.parsedResult : (completedJob.rawOutput == null ? "" : completedJob.rawOutput.trim());
          return ResponseEntity.ok(Map.of(
              "sessionId", sessionId,
              "jobId", jobId,
              "status", STATUS_COMPLETED,
              "result", result
          ));
        }
        if (STATUS_FAILED.equals(completedJob.status)) {
          String errorText = completedJob.error != null ? completedJob.error : completedJob.rawOutput;
          if (isNoFaceError(errorText)) {
            return ResponseEntity.unprocessableEntity().body(Map.of(
                "sessionId", sessionId,
                "jobId", jobId,
                "error", "No face detected in video frames"
            ));
          }
          return ResponseEntity.status(500).body(Map.of(
              "sessionId", sessionId,
              "jobId", jobId,
              "error", "Fusion failed: " + (errorText == null ? "Unknown error" : errorText)
          ));
        }
      } catch (TimeoutException timeoutException) {
        writeLog("/fuse-files", "TIMEOUT", "Job " + jobId + " still processing after wait timeout");
      }
    }

    return ResponseEntity.accepted().body(Map.of(
        "sessionId", sessionId,
        "jobId", jobId,
        "status", STATUS_QUEUED,
        "message", "Fusion job started",
        "statusEndpoint", "/api/v1/lipreading/avsr/fuse-files/status/" + jobId
    ));
  }

  @GetMapping("/avsr/fuse-files/status/{jobId}")
  public ResponseEntity<Object> fuseFilesStatus(@PathVariable String jobId) {
    FusionJob job = fusionJobs.get(jobId);
    if (job == null) {
      return ResponseEntity.status(404).body(Map.of(
          "jobId", jobId,
          "status", "NOT_FOUND",
          "message", "No fusion job found"));
    }

    return buildJobResponse(jobId, job);
  }

  private ResponseEntity<Object> buildJobResponse(String jobId, FusionJob job) {
    if (job == null) {
      return ResponseEntity.status(404).body(Map.of(
          "jobId", jobId,
          "status", "NOT_FOUND",
          "message", "No fusion job found"));
    }

    Map<String, Object> response = new LinkedHashMap<>();
    response.put("jobId", jobId);
    response.put("status", job.status);

    if (STATUS_COMPLETED.equals(job.status)) {
      if (job.parsedResult != null) {
        return ResponseEntity.ok(job.parsedResult);
      }
      return ResponseEntity.ok(job.rawOutput == null ? "" : job.rawOutput.trim());
    }
    if (STATUS_FAILED.equals(job.status)) {
      response.put("error", job.error);
      response.put("rawOutput", job.rawOutput);
      if (isNoFaceError(job.error)) {
        return ResponseEntity.unprocessableEntity().body(response);
      }
      return ResponseEntity.status(500).body(response);
    }
    return ResponseEntity.ok(response);
  }

  private boolean isNoFaceError(String message) {
    if (message == null) {
      return false;
    }
    String normalized = message.toLowerCase(Locale.ROOT);
    return normalized.contains("no face detected");
  }

  private String extractAudioText(JsonNode parsedResult) {
    if (parsedResult == null) {
      return null;
    }
    JsonNode snake = parsedResult.get("audio_text");
    if (snake != null && !snake.isNull()) {
      return snake.asText(null);
    }
    JsonNode camel = parsedResult.get("audioText");
    if (camel != null && !camel.isNull()) {
      return camel.asText(null);
    }
    return null;
  }

  private void runFusionJob(String jobId, Path audioTemp, Path videoTemp) {
    FusionJob job = fusionJobs.get(jobId);
    if (job == null) {
      deleteQuietly(audioTemp);
      deleteQuietly(videoTemp);
      return;
    }

    job.status = STATUS_PROCESSING;
    try {
      String resultText;
      try {
        resultText = invokeFusionViaWorker(audioTemp, videoTemp, false, null);
      } catch (Exception workerException) {
        log.warn("Worker fusion failed for job {}, falling back to one-shot script", jobId, workerException);
        writeLog("/fuse-files", "WARN", "Worker fallback for job " + jobId + ": " + workerException.getMessage());
        resultText = invokeFusionStandalone(audioTemp, videoTemp, false, null);
      }

      log.info("Fusion job {} completed successfully.", jobId);
      writeLog("/fuse-files", "SUCCESS", "Job " + jobId + " completed");
      job.rawOutput = resultText;
      job.parsedResult = extractLastJsonObject(resultText);
      job.status = STATUS_COMPLETED;
      persistFusionSession(job, null);
    } catch (Exception ex) {
      log.error("AVSR fusion job {} crashed", jobId, ex);
      writeLog("/fuse-files", "EXCEPTION", "Job " + jobId + " crashed: " + ex.getMessage());
      job.status = STATUS_FAILED;
      job.error = ex.getClass().getSimpleName() + ": " + ex.getMessage();
      persistFusionSession(job, ex);
    } finally {
      deleteQuietly(audioTemp);
      deleteQuietly(videoTemp);
    }
  }

  private String invokeFusionViaWorker(Path audioTemp, Path videoTemp) throws Exception {
    return invokeFusionViaWorker(audioTemp, videoTemp, false, null);
  }

  private void runFusionJob(String jobId, Path audioTemp, Path videoTemp, boolean fast, Integer frameCount) {
    FusionJob job = fusionJobs.get(jobId);
    if (job == null) {
      deleteQuietly(audioTemp);
      deleteQuietly(videoTemp);
      return;
    }

    job.status = STATUS_PROCESSING;
    try {
      String resultText;
      try {
        resultText = invokeFusionViaWorker(audioTemp, videoTemp, fast, frameCount);
      } catch (Exception workerException) {
        log.warn("Worker fusion failed for job {}, falling back to one-shot script", jobId, workerException);
        writeLog("/fuse-files", "WARN", "Worker fallback for job " + jobId + ": " + workerException.getMessage());
        resultText = invokeFusionStandalone(audioTemp, videoTemp, fast, frameCount);
      }

      log.info("Fusion job {} completed successfully.", jobId);
      writeLog("/fuse-files", "SUCCESS", "Job " + jobId + " completed");
      job.rawOutput = resultText;
      job.parsedResult = extractLastJsonObject(resultText);
      job.status = STATUS_COMPLETED;
      persistFusionSession(job, null);
    } catch (Exception ex) {
      log.error("AVSR fusion job {} crashed", jobId, ex);
      writeLog("/fuse-files", "EXCEPTION", "Job " + jobId + " crashed: " + ex.getMessage());
      job.status = STATUS_FAILED;
      job.error = ex.getClass().getSimpleName() + ": " + ex.getMessage();
      persistFusionSession(job, ex);
    } finally {
      deleteQuietly(audioTemp);
      deleteQuietly(videoTemp);
    }
  }

  private String invokeFusionViaWorker(Path audioTemp, Path videoTemp, boolean fast, Integer frameCount) throws Exception {
    synchronized (fusionWorkerLock) {
      ensureFusionWorkerStarted();

      Map<String, Object> request = new LinkedHashMap<>();
      request.put("audioPath", audioTemp.toAbsolutePath().toString());
      request.put("videoPath", videoTemp.toAbsolutePath().toString());
      request.put("fast", fast);
      if (frameCount != null) {
        request.put("frameCount", frameCount);
      }

      fusionWorkerStdin.write(OBJECT_MAPPER.writeValueAsString(request));
      fusionWorkerStdin.newLine();
      fusionWorkerStdin.flush();

      String responseLine = readLineWithTimeout(fusionWorkerStdout, fusionWorkerProcess, 180);
      if (responseLine == null) {
        stopFusionWorker();
        throw new IOException("Worker closed stdout unexpectedly");
      }

      JsonNode response = OBJECT_MAPPER.readTree(responseLine);
      if (!response.path("ok").asBoolean(false)) {
        throw new IOException(response.path("error").asText("Worker returned unknown error"));
      }

      return response.path("rawOutput").asText("");
    }
  }

  private String invokeFusionStandalone(Path audioTemp, Path videoTemp, boolean fast, Integer frameCount) throws Exception {
    java.util.List<String> command = new java.util.ArrayList<>();
    command.add(resolveWhisperPythonExecutable());
    command.add("avsr_batch_fusion.py");
    command.add(audioTemp.toAbsolutePath().toString());
    command.add(videoTemp.toAbsolutePath().toString());
    if (frameCount != null) {
      command.add(String.valueOf(frameCount));
    } else if (fast) {
      command.add("25");
    }

    ProcessBuilder pb = new ProcessBuilder(command);
    pb.directory(new File(AVSR_WORK_DIR));
    pb.redirectErrorStream(true);
    Process process = pb.start();

    StringBuilder output = new StringBuilder();
    try (java.io.BufferedReader reader = new java.io.BufferedReader(
        new java.io.InputStreamReader(process.getInputStream(), java.nio.charset.StandardCharsets.UTF_8))) {
      String line;
      while ((line = reader.readLine()) != null) {
        output.append(line).append("\n");
      }
    }

    int exitCode = process.waitFor();
    if (exitCode != 0) {
      throw new IOException(output.toString());
    }
    return output.toString();
  }

  private void ensureFusionWorkerStarted() throws IOException {
    if (fusionWorkerProcess != null && fusionWorkerProcess.isAlive() && fusionWorkerStdin != null && fusionWorkerStdout != null) {
      return;
    }

    stopFusionWorker();

    ProcessBuilder workerPb = new ProcessBuilder(resolveWhisperPythonExecutable(), AVSR_WORKER_SCRIPT);
    workerPb.directory(new File(AVSR_WORK_DIR));
    workerPb.redirectErrorStream(false);
    Process process = workerPb.start();

    java.io.BufferedWriter stdin = new java.io.BufferedWriter(
        new java.io.OutputStreamWriter(process.getOutputStream(), java.nio.charset.StandardCharsets.UTF_8));
    java.io.BufferedReader stdout = new java.io.BufferedReader(
        new java.io.InputStreamReader(process.getInputStream(), java.nio.charset.StandardCharsets.UTF_8));
    java.io.BufferedReader stderr = new java.io.BufferedReader(
        new java.io.InputStreamReader(process.getErrorStream(), java.nio.charset.StandardCharsets.UTF_8));

    Thread stderrDrainer = new Thread(() -> {
      try {
        String line;
        while ((line = stderr.readLine()) != null) {
          log.debug("[avsr-worker] {}", line);
        }
      } catch (IOException ignored) {
      }
    }, "avsr-worker-stderr");
    stderrDrainer.setDaemon(true);
    stderrDrainer.start();

    fusionWorkerProcess = process;
    fusionWorkerStdin = stdin;
    fusionWorkerStdout = stdout;
  }

  private void stopFusionWorker() {
    synchronized (fusionWorkerLock) {
      if (fusionWorkerStdin != null) {
        try {
          fusionWorkerStdin.close();
        } catch (IOException ignored) {
        }
      }
      if (fusionWorkerStdout != null) {
        try {
          fusionWorkerStdout.close();
        } catch (IOException ignored) {
        }
      }
      if (fusionWorkerProcess != null) {
        if (fusionWorkerProcess.isAlive()) {
          fusionWorkerProcess.destroy();
          try {
            if (!fusionWorkerProcess.waitFor(3, TimeUnit.SECONDS)) {
              fusionWorkerProcess.destroyForcibly();
              fusionWorkerProcess.waitFor(2, TimeUnit.SECONDS);
            }
          } catch (InterruptedException ignored) {
            fusionWorkerProcess.destroyForcibly();
          }
        }
      }

      fusionWorkerStdin = null;
      fusionWorkerStdout = null;
      fusionWorkerProcess = null;
    }
  }

  private JsonNode extractLastJsonObject(String output) {
    if (output == null || output.isBlank()) {
      return null;
    }

    int start = output.lastIndexOf('{');
    if (start < 0) {
      return null;
    }

    String candidate = output.substring(start).trim();
    try {
      return OBJECT_MAPPER.readTree(candidate);
    } catch (Exception ignored) {
      return null;
    }
  }

      @ExceptionHandler(Exception.class)
      public ResponseEntity<String> handleException(Exception ex) {
        writeLog("/error", "EXCEPTION", ex.getClass().getSimpleName() + ": " + ex.getMessage());
        return ResponseEntity.status(500).body("Error: " + ex.getMessage());
      }
  @PostMapping(value = "/avsr/upload-audio", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
  public ResponseEntity<String> uploadAudio(
      @RequestParam("audioFile") MultipartFile audioFile) throws Exception {
    // SecurityUtils.currentPrincipal(); // ensure authenticated
    log.info("Received audio upload request");

    if (audioFile == null || audioFile.isEmpty()) {
      throw new IllegalArgumentException("audioFile is required");
    }

    Path audioTemp = null;
    try {
      audioTemp = Files.createTempFile("avsr-audio-", extensionOf(audioFile.getOriginalFilename()));
      audioFile.transferTo(audioTemp);

      // Use persistent audio worker for fast inference
      String result = invokeAudioWorker(audioTemp);
      // Return JSON object with 'result' field
      String json = OBJECT_MAPPER.writeValueAsString(Map.of("result", result));
      return ResponseEntity.ok()
          .contentType(MediaType.APPLICATION_JSON)
          .body(json);
    } finally {
      deleteQuietly(audioTemp);
    }
  }

  // Persistent audio worker invocation
  private String invokeAudioWorker(Path audioTemp) throws Exception {
    synchronized (audioWorkerLock) {
      IOException lastError = null;
      for (int attempt = 0; attempt < 2; attempt++) {
        ensureAudioWorkerStarted();
        Map<String, Object> request = new LinkedHashMap<>();
        request.put("audioPath", audioTemp.toAbsolutePath().toString());
        audioWorkerStdin.write(OBJECT_MAPPER.writeValueAsString(request));
        audioWorkerStdin.newLine();
        audioWorkerStdin.flush();
        String responseLine = readLineWithTimeout(audioWorkerStdout, audioWorkerProcess, 120);
        if (responseLine == null) {
          stopAudioWorker();
          lastError = new IOException("Audio worker closed stdout unexpectedly");
          log.warn("Audio worker died on attempt {}, restarting...", attempt + 1);
          continue;
        }
        JsonNode response = OBJECT_MAPPER.readTree(responseLine);
        if (!response.has("result")) {
          throw new IOException("Audio worker did not return a 'result' field: " + responseLine);
        }
        return response.path("result").asText("");
      }
      throw lastError;
    }
  }

  private void ensureAudioWorkerStarted() throws IOException {
    if (audioWorkerProcess != null && audioWorkerProcess.isAlive() && audioWorkerStdin != null && audioWorkerStdout != null) {
      return;
    }
    stopAudioWorker();
    String pythonExe = resolveWhisperPythonExecutable();
    ProcessBuilder workerPb = new ProcessBuilder(pythonExe, AUDIO_WORKER_SCRIPT);
    workerPb.directory(new File(AUDIO_WORK_DIR));
    workerPb.redirectErrorStream(false);
    Process process = workerPb.start();
    java.io.BufferedWriter stdin = new java.io.BufferedWriter(
        new java.io.OutputStreamWriter(process.getOutputStream(), java.nio.charset.StandardCharsets.UTF_8));
    java.io.BufferedReader stdout = new java.io.BufferedReader(
        new java.io.InputStreamReader(process.getInputStream(), java.nio.charset.StandardCharsets.UTF_8));
    java.io.BufferedReader stderr = new java.io.BufferedReader(
        new java.io.InputStreamReader(process.getErrorStream(), java.nio.charset.StandardCharsets.UTF_8));
    Thread stderrDrainer = new Thread(() -> {
      try {
        String line;
        while ((line = stderr.readLine()) != null) {
          log.debug("[audio-worker] {}", line);
        }
      } catch (IOException ignored) {}
    }, "audio-worker-stderr");
    stderrDrainer.setDaemon(true);
    stderrDrainer.start();
    audioWorkerProcess = process;
    audioWorkerStdin = stdin;
    audioWorkerStdout = stdout;
  }

  private String resolveWhisperPythonExecutable() {
    String[] candidates = {
        System.getenv("AVSR_WHISPER_PYTHON"),
        System.getenv("AVSR_ASR_PYTHON"),
        "python",
        "python3",
        "py"
    };

    for (String candidate : candidates) {
      if (candidate == null || candidate.isBlank()) {
        continue;
      }
      if (canImportWhisper(candidate)) {
        return candidate;
      }
    }

    log.warn("No Python interpreter with Whisper was found; falling back to 'python'. Set AVSR_WHISPER_PYTHON to a working interpreter.");
    return "python";
  }

  private boolean canImportWhisper(String pythonExe) {
    Process process = null;
    try {
      ProcessBuilder processBuilder = new ProcessBuilder(pythonExe, "-c", "import whisper");
      processBuilder.redirectErrorStream(true);
      process = processBuilder.start();
      if (!process.waitFor(10, TimeUnit.SECONDS)) {
        process.destroyForcibly();
        return false;
      }
      return process.exitValue() == 0;
    } catch (Exception ex) {
      return false;
    } finally {
      if (process != null) {
        process.destroy();
      }
    }
  }

  private void stopAudioWorker() {
    synchronized (audioWorkerLock) {
      if (audioWorkerStdin != null) {
        try { audioWorkerStdin.close(); } catch (IOException ignored) {}
      }
      if (audioWorkerStdout != null) {
        try { audioWorkerStdout.close(); } catch (IOException ignored) {}
      }
      if (audioWorkerProcess != null) {
        if (audioWorkerProcess.isAlive()) {
          audioWorkerProcess.destroy();
          try {
            if (!audioWorkerProcess.waitFor(3, TimeUnit.SECONDS)) {
              audioWorkerProcess.destroyForcibly();
              audioWorkerProcess.waitFor(2, TimeUnit.SECONDS);
            }
          } catch (InterruptedException ignored) {
            audioWorkerProcess.destroyForcibly();
          }
        }
      }
      audioWorkerStdin = null;
      audioWorkerStdout = null;
      audioWorkerProcess = null;
    }
  }
  

  @PostMapping(value = "/avsr/upload-video", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
  public ResponseEntity<String> uploadVideo(
      @RequestParam("videoFile") MultipartFile videoFile)
      throws Exception {
    // SecurityUtils.currentPrincipal(); // ensure authenticated
    log.info("Received video upload request");

    if (videoFile == null || videoFile.isEmpty()) {
      throw new IllegalArgumentException("videoFile is required");
    }

    Path videoTemp = null;
    try {
      videoTemp = Files.createTempFile("avsr-video-", extensionOf(videoFile.getOriginalFilename()));
      videoFile.transferTo(videoTemp);

      // TODO: Process video file as needed
      return ResponseEntity.ok("Video uploaded: " + videoTemp.toAbsolutePath());
    } finally {
      deleteQuietly(videoTemp);
    }
  }

  private String readLineWithTimeout(java.io.BufferedReader reader, Process process, long timeoutSecs) throws IOException {
    Thread killer = new Thread(() -> {
      try {
        Thread.sleep(timeoutSecs * 1000);
        if (process.isAlive()) {
          process.destroyForcibly();
        }
      } catch (InterruptedException ignored) {}
    }, "worker-killer");
    killer.setDaemon(true);
    killer.start();
    try {
      return reader.readLine();
    } finally {
      killer.interrupt();
    }
  }

  private void deleteQuietly(Path path) {
    if (path == null) {
      return;
    }
    try {
      Files.deleteIfExists(path);
    } catch (Exception ignored) {
    }
  }

  private String extensionOf(String fileName) {
    if (fileName == null) {
      return ".tmp";
    }
    String normalized = fileName.trim().toLowerCase(Locale.ROOT);
    int dot = normalized.lastIndexOf('.');
    if (dot <= -1 || dot == normalized.length() - 1) {
      return ".tmp";
    }
    return normalized.substring(dot);
  }

  private void persistFusionSession(FusionJob job, Exception ex) {
    if (job == null || job.userId == null || job.userId.isBlank()) {
      return;
    }
    if (STATUS_COMPLETED.equals(job.status)) {
      String resultText = extractFusionResultText(job.parsedResult);
      if (resultText == null && job.rawOutput != null) {
        resultText = job.rawOutput.trim();
      }
      Double accuracyScore = extractFusionConfidence(job.parsedResult);
      String content = buildAvsrHistoryContent(job, ex);
      saveCompletedSession(
          job.userId,
          SessionInputType.RECORDED,
          SessionOutputType.TEXT,
          resultText,
          null,
          accuracyScore,
          content
      );
      return;
    }

    String error = ex != null ? ex.getMessage() : job.error;
    String content = buildAvsrHistoryContent(job, ex);
    saveFailedSession(
        job.userId,
        SessionInputType.RECORDED,
        SessionOutputType.TEXT,
        error,
        content
    );
  }

  private Double extractFusionConfidence(JsonNode parsedResult) {
    if (parsedResult == null) {
      return null;
    }

    JsonNode fused = parsedResult.get("fused_conf");
    if (fused != null && fused.isNumber()) {
      return fused.asDouble();
    }

    JsonNode lip = parsedResult.get("lip_conf");
    if (lip != null && lip.isNumber()) {
      return lip.asDouble();
    }

    return null;
  }

  private String buildAvsrHistoryContent(FusionJob job, Exception ex) {
    Map<String, Object> payload = new LinkedHashMap<>();
    payload.put("source", "avsr");
    payload.put("status", job == null ? null : job.status);

    if (job != null && job.parsedResult != null) {
      payload.put("result", job.parsedResult);
    } else if (job != null && job.rawOutput != null && !job.rawOutput.isBlank()) {
      payload.put("rawOutput", job.rawOutput.trim());
    }

    String error = ex != null ? ex.getMessage() : (job == null ? null : job.error);
    if (error != null && !error.isBlank()) {
      payload.put("error", error);
    }

    return jsonToCompactString(OBJECT_MAPPER.valueToTree(payload));
  }

  private String extractFusionResultText(JsonNode parsedResult) {
    if (parsedResult == null) {
      return null;
    }

    String[] preferredFields = {
        "finalWord",
        "final_word",
        "matchedLipWord",
        "matched_lip_word",
        "audioText",
        "audio_text",
        "recognizedText",
        "recognized_text"
    };

    for (String field : preferredFields) {
      JsonNode node = parsedResult.get(field);
      if (node != null && !node.isNull() && !node.asText("").isBlank()) {
        return node.asText();
      }
    }

    return jsonToCompactString(parsedResult);
  }

  private String jsonToCompactString(JsonNode node) {
    try {
      return OBJECT_MAPPER.writeValueAsString(node);
    } catch (Exception ignored) {
      return node == null ? null : node.toString();
    }
  }

  private void saveCompletedSession(
      String userId,
      SessionInputType inputType,
      SessionOutputType outputType,
      String resultText,
      String resultAudioUrl,
      Double accuracyScore,
      String content
  ) {
    try {
      sessionService.recordCompleted(userId, inputType, outputType, resultText, resultAudioUrl, accuracyScore, content);
    } catch (Exception saveEx) {
      log.warn("Failed to persist completed session history", saveEx);
    }
  }

  private void saveFailedSession(
      String userId,
      SessionInputType inputType,
      SessionOutputType outputType,
      String errorText,
      String content
  ) {
    try {
      sessionService.recordFailed(userId, inputType, outputType, errorText, content);
    } catch (Exception saveEx) {
      log.warn("Failed to persist failed session history", saveEx);
    }
  }
}
